### ISSUE TITLE
Thumbnails don't respond to click if selection preview active

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#276]
If there's a selection preview active (thanks @jeremybmerrill for the fix!), the thumbnails stop responding 
to clicks. Easily fixed with:

```css
.selection-show {
pointer-events: none;
}
```
