### ISSUE TITLE
Long filenames push buttons out of viewport

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#283]
Truncate them, maybe?

```css
.truncate {
  width: 250px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

![screen shot 2015-03-11 at 11 14 41 am](https://cloud.githubusercontent.com/assets/27584/6599391/e79d0772-c7df-11e4-9934-9fca3c474318.png)
